language: ruby
sudo: required
dist: trusty

branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  
services: docker

env:
  global:
    - ENV="ci"
    - secure: "4E8X5K2DTCorKESSqhFWO4UsTVUuoGO9uVO7Vol9obe/dH/PqQvGLmJ7zzr5TTxbaZZw89JJTo22Czxcita/f1hcZTD4xjNP2dEPTjfF2yW3t2M2796FwYkXvNMSaXg1x8nVTw0YsNZmby/Yx20mnTDK5vRb+zPMfsCENUOw48rx4PeRh+ko8WRACrJb+6FUlQ8gOrTLoiuOkkydwzLt0k0kiLh3P/tFCYS5bkxrhXKeX6ivIlROPRVkwE69r9ARCiBoGqQL0gZ6DH7+X5Psxw3ryh+AT16xnUXApp8cCCxY12Iau4p65wB+rOP2JBgNgKyvvh4YqQoh30Cjv8vQHB3htg2hQHJiLwcMRkj5B02mxGQxEoSEi9M8hmYwGcUHVbCM4a8APsaBPX0s+bL/pHlxz3lNvXBpl6mqG5rjGY+S+lskNiAPSBWRmZVz0AdFeBiXHUe5pZR7Nk0eUpsJ5vFhrXPqbtVfhIw43J3mYvTlythGHyoWrOUFGiGGqRy9ALDpQJszGdJJiTJZUfTq2WgfuH8PzOuEVCY8lIfZ0R94O+o4jrRwngx0p2AeyZ0Ojg1jd1qyXGs7pOpvhXTusgxsD+cM6rIKXhpWegKMZZ3kzKELlNrSYSaoCCfFJWPkr6zywAjpxQEcENWUevzRqKiSoS3oGLFroHs/D4JjhMI="

addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk

install:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script:
  - chef exec rake
  
before_deploy:
  - openssl aes-256-cbc -K $encrypted_dbbf163e797a_key -iv $encrypted_dbbf163e797a_iv -in codenamephp.pem.enc -out codenamephp.pem -d
  - git config --local user.name "Travis CI"
  - git config --local user.email "travis@codename-php.de"
  - git remote set-url --push origin "https://$GH_TOKEN@github.com/codenamephp/chef.cookbook.chef.git"
deploy:
  - provider: script
    on:
      branch: master
    skip_cleanup: true
    script: chef exec rake release
  
notifications:
  slack: codenamephp:4LpipONUdfAZ5ebatYC7Egmb
